### ISSUE TITLE
Allow indexing fields from related models

### ISSUE THREAD

**Issue by zgoda** [honmaple/flask-msearch#1]
I have 2 models related by foreign key and I would like to search data from related model, eg Author and Book so I could search for both author name and book title. I can create artificial field that concatenates all fields I want to have searchable but this is inconvenient.

This could be like eg:

```python
class Book(db.Model):
    __searchable__ = ['title', 'summary', 'author.full_name']
```

where `author` is `db.relationship` based on foreign key

**Comment by honmaple** [comment]
Thank you for your support,at present flask-msearch doesn't support relationship column,I will add it in the future.

**Comment by zgoda** [comment]
Okay, I'm working on a PR that would allow some workaround using SQLAlchemy [hybrid_property](http://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html). Basically one change to `_schema()` method to detect that this is not a "normal" field.

**Comment by honmaple** [comment]
Related models has been added  on https://github.com/honmaple/flask-msearch/commit/fe4544f8381748fc24e73fd1155ae0928ce04bb6
