### ISSUE TITLE
i got an error at import_string where run init_app

### ISSUE THREAD

**Issue by goodking-bq** [honmaple/flask-msearch#14]
werkzeug.utils.ImportStringError: import_string() failed for 'flask_msearch.whoosh_backend'.

**Comment by shenhy123** [comment]
For version 1.0.0 werkzeug, import ‘import_string’ should use
`from werkzeug.utils import import_string`

My solution is to add the following line of code in `site-packages\werkzeug\__init__.py` file .

`from .utils import import_string`
