### ISSUE TITLE
no attribute 'create_index'

### ISSUE THREAD

**Issue by johnroper100** [honmaple/flask-msearch#16]
I'm getting this error when trying to use this. `AttributeError: 'function' object has no attribute 'create_index'`

**Comment by johnroper100** [comment]
oh, that makes sense

**Comment by johnroper100** [comment]
That fixed it. Is there a way that you can set where the msearch folder goes? Other than the root directory where the script is.

**Comment by honmaple** [comment]
You can set `MSEARCH_INDEX_NAME="/tmp/anyfolder"`

**Comment by johnroper100** [comment]
Ok, thanks
