### ISSUE TITLE
ERROR:flask.app:msearch() takes 3 positional arguments but 6 were given

### ISSUE THREAD

**Issue by jiabotao1989** [honmaple/flask-msearch#18]
您好，当我换成elasticsearch引擎后，就报错ERROR:flask.app:msearch() takes 3 positional arguments but 6 were given，但是我的参数的确是三个，查询语句是
comp = Comp.query.msearch(name, fields=['EntName'], limit=10)，没有什么问题，找不到原因

**Comment by honmaple** [comment]
elasticsearch问题已修复，请下载最新版测试 `pip install flask-msearch --upgrade`

**Comment by honmaple** [comment]
Reopen if needed.
