### ISSUE TITLE
exception when using alternate class attribute for primary key

### ISSUE THREAD

**Issue by coreybrett** [honmaple/flask-msearch#19]
My models use 'pk' for the primary key instead of 'id'.

I tried changing line 28 of flask_msearch/whoosh_backend.py to `DEFAULT_PRIMARY_KEY = 'pk'` but that didn't seem to work. Is there a proper way to add this to the config?

**Comment by honmaple** [comment]
Sorry for late reply. I have add custom primary key parameter, you can set global primary key by
```
MSEARCH_PRIMARY_KEY = "pk"
```
or set `__msearch_primary_key__` for special model
