### ISSUE TITLE
when should I call search.create_index(update=True)

### ISSUE THREAD

**Issue by coreybrett** [honmaple/flask-msearch#20]
When adding flask-msearch to an existing app/database, do I need to call `search.create_index(update=True)` manually? If so, where would the best place for that be?

**Comment by honmaple** [comment]
Call `search.create_index()`  once manually before you start the service. 
When `MSEARCH_ENABLE = True` flask-msearch will auto update database,so  you needn't place  `search.create_index(update=True)` to any location.

**Comment by honmaple** [comment]
Reopen if needed.
