### ISSUE TITLE
MySQL timeout with big db

### ISSUE THREAD

**Issue by johnroper100** [honmaple/flask-msearch#26]
I have a big database using flask and MySQL. It has about 1,060,000 items to search and index. I'm trying to update the search index for all the items at once using `search.update_index()` however, MySQL keeps timing out halfway through. Any ideas on how to fix this?

**Comment by honmaple** [comment]
Why use `update_index` rather than `create_index`?

You can use `update_index(yield_per=1000)` or `create_index(yield_per=1000)` for big data, please check output of log

**Comment by johnroper100** [comment]
Ok, I'll try that

**Comment by johnroper100** [comment]
It didn't work. Here is a picture of my error:
![Screenshot from 2019-07-23 19-15-29](https://user-images.githubusercontent.com/9782943/61753745-6bf1bd00-ad7e-11e9-927f-6325c8122235.png)

**Comment by honmaple** [comment]
This looks like a problem about database connection.

**Comment by johnroper100** [comment]
Yes, the site is working fine, and the regular search.update_one_index calls are also working fine, it's just the search.update_index that's not working

**Comment by honmaple** [comment]
What's you configuration of `sqlalchemy`, maybe it's a issue about `SQLALCHEMY_POOL_RECYCLE` or `SQLALCHEMY_POOL_TIMEOUT`

Similar problem https://stackoverflow.com/questions/42163359/flask-sqlalchemy-2013-lost-connection
