### ISSUE TITLE
Woosh lock error with big site

### ISSUE THREAD

**Issue by johnroper100** [honmaple/flask-msearch#27]
Hi, I am running a fairly big site that has many users per day, however, this causes an issue when updating search because I am getting whoosh.index.LockError a lot. Obviously this is due to the high usage. How can I fix this (other than just doing something to block the error ie. try/except)?

**Comment by honmaple** [comment]
`flask-msearch` uses flask signal to update index by default. If the amount of data is large, it will take up high memory.
Therefore, my suggestion is to use other python asynchronous tools to update the index when the amount of data is large, such as `celery` and `rq`

**Comment by johnroper100** [comment]
Are you able to give a small example instead of just calling `search.update_one_index(Item)`?

**Comment by honmaple** [comment]
```
@celery.task(bind=True)
def update_index(self, instance, update=False, delete=False, commit=True):
    search.create_one_index(instance, update, delete, commit)
    return str(self.request.id)
```
Using `update_index.delay(instance, update=True` instead of `self.create_one_index(instance, update=True)`
