### ISSUE TITLE
Bug in related index updates

### ISSUE THREAD

**Issue by fhscholl** [honmaple/flask-msearch#30]
signal.py Line 55: `ix.update(**backend._fields(instance, attr))`

I believe `instance` is incorrect here. It will work in cases where the name of the primary key is the same, but if the name of the primary key is different `_fields` will try to pop the wrong value. There is no need to use `_fields` at all here, really, since there is already a reference to the target index.

`ix.update(**{ix.pk: attr.pop(ix.pk), "body": {"doc": attr}})`

**Comment by honmaple** [comment]
Thank you for your report, I will fix it.

`_fields` is neccessary, because whoosh's `_fields` and elasticsearch's `_fields` is different.

**Comment by honmaple** [comment]
https://github.com/honmaple/flask-msearch/commit/c9d2ed778c6cdb91e7579152666083ec428e4cac
