### ISSUE TITLE
ImportError: cannot import name 'import_string' from 'werkzeug'

### ISSUE THREAD

**Issue by dilless** [honmaple/flask-msearch#36]
When I run flask server, i got the error:
`ImportError: cannot import name 'import_string' from 'werkzeug'`
I have seen the issues, and found that this error had been sovled by previous 'pull requests'. But  I still got this error, and I have to modify the source code every time when I install this package to sovle this problem.
I installed flask-msearch by pipenv.
What should I do? Install the package manually install of pypi?
Thanks!

**Comment by honmaple** [comment]
Well, I forgot to upload to the pypi. Now the newest version `0.2.7` has been uploaded, please check it.

**Comment by dilless** [comment]
The problem has been fixed. Thanks
