### ISSUE TITLE
[Feature Request] - Return whoosh result object along with each result

### ISSUE THREAD

**Issue by veeshi** [honmaple/flask-msearch#42]
It would be useful to have an option to return the whoosh result object along with each result.

One use case is so we can then at a later stage highlight the matched terms in each result.

Whoosh Documentation - [“Did you mean... ?” Correcting errors in user queries](https://whoosh.readthedocs.io/en/latest/searching.html#which-terms-from-my-query-matched)

**Comment by honmaple** [comment]
For convenience, `flask-msearch` always return a `Model` , if you want to use origin whoosh syntax, you can use
```
search = Search()

....
search.msearch(Post, "apple", fields=None, limit=None, or_=True)
```

**Comment by veeshi** [comment]
Apologies, I'm interested in the whoosh.searching.Results and whoosh.searching.Hit objects so I can view which search terms matched and highlight the matching terms in the results.
References:
[Which terms from my query matched?](https://whoosh.readthedocs.io/en/latest/searching.html#which-terms-from-my-query-matched)
[How to create highlighted search result excerpts](https://whoosh.readthedocs.io/en/latest/highlight.html)
