### ISSUE TITLE
'Query' object has no attribute '_mapper_zero'

### ISSUE THREAD

**Issue by ptitoliv** [honmaple/flask-msearch#51]
Hello,

I'm trying to use flask-msearch on my exisiting application. When I try to execute a FTS query on my table, I get the following error :  `'Query' object has no attribute '_mapper_zero'`

My table is described as the following :  

```python
class Movie(db.Model):       
 __tablename__ = "movies"
        __searchable__ = [ 'name' ]
        #__table_args__ = {'mysql_charset': 'utf8', 'mysql_collate': 'utf8_general_ci'}
        # Settings for FTS (WooshAlchemy)
        __searchable__ = [ 'name', 'director', 'original_name' ]
        charmap = charset_table_to_dict(default_charset)
        __msearch_analyzer__ = NgramWordAnalyzer(3) | CharsetFilter(charmap)
```

I unfortunately don't understand why I have such an error. I tried to investigate the code of the whoosh_backend but without success :(

Is there something weird in that code ?

Thanks for your support !

**Comment by honmaple** [comment]
https://github.com/honmaple/flask-msearch/issues/50
