### ISSUE TITLE
'SimpleSearch' object has no attribute 'index'

### ISSUE THREAD

**Issue by yxm0513** [honmaple/flask-msearch#56]
File "/usr/local/lib/python3.9/site-packages/flask_msearch/backends.py", line 159, in create_index
    return self.create_all_index(update, delete)
  File "/usr/local/lib/python3.9/site-packages/flask_msearch/backends.py", line 172, in create_all_index
    ix = self.create_index(m, update, delete, yield_per)
  File "/usr/local/lib/python3.9/site-packages/flask_msearch/backends.py", line 160, in create_index
    ix = self.index(model)
AttributeError: 'SimpleSearch' object has no attribute 'index'

I didn't see the index method definition

    def create_index(self,
                     model='__all__',
                     update=False,
                     delete=False,
                     yield_per=100):
        if model == '__all__':
            return self.create_all_index(update, delete)
        ix = self.index(model)                                          ----> issue here
        instances = model.query.enable_eagerloads(False).yield_per(yield_per)
        for instance in instances:
            self.create_one_index(instance, update, delete, False)
        ix.commit()
        return ix

**Comment by honmaple** [comment]
Please use `whoosh`. `SimpleSearch` don't support functions about index
