### ISSUE TITLE
AttributeError AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by IRafique2** [honmaple/flask-msearch#58]

**Comment by IRafique2** [comment]
@app.route('/' )
def w_search():
   searchword = request.args.get('q')
   products = AddProduct.query.msearch(searchword, fields=['title'], limit=3)
   return render_template('search.html')
and this is my html page

<div class="container">
  <form method="GET" action="{{url_for('w_search')}}">
  
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"  name="q">
    <button class="btn btn-outline-success mt-3" type="submit">Search</button>
  
  </form>

**Comment by honmaple** [comment]
`searchword = request.args.get('q')` return `None`, you should check searchword is not empty first
