### ISSUE TITLE
请问一下中文为什么搜索为null

### ISSUE THREAD

**Issue by hwpchn** [honmaple/flask-msearch#6]
英文可以正确搜索出来

**Comment by honmaple** [comment]
默认的analyzer对中文不太友好，你可以自定义它，比如使用
```
from jieba.analyse import ChineseAnalyzer
search = Search(analyzer=ChineseAnalyzer())
```

**Comment by thunderwin** [comment]
https://forums.honmaple.org/search?keyword=%E6%AF%95%E4%B8%9A&include=0  在你给的Demo 中搜索 ‘毕业’ 为什么是空，明明有很多文章包含

**Comment by honmaple** [comment]
我机器配置很低，所以使用默认的analyzer，没有使用jieba分词
