### ISSUE TITLE
出现这样的错误

### ISSUE THREAD

**Issue by thunderwin** [honmaple/flask-msearch#7]
AttributeError: 'function' object has no attribute 'msearch'

**Comment by honmaple** [comment]
可以具体一些吗？ 是不是没有调用 `search.init_app(app)`

**Comment by seale** [comment]
@honmaple 我也有类似的疑问，测试时`search.create_index()`放在视图函数之前就可以，放在后面会报错：
```py
AttributeError: 'function' object has no attribute 'create_index' 
```
