### ISSUE TITLE
我测试搜索数据库里存在的关键字后没有返回数据，不知道是哪里没设置好

### ISSUE THREAD

**Issue by seale** [honmaple/flask-msearch#8]
大部分用的是你项目readme文件的代码，搜索英文中文都没返回
打印了搜索语句返回结果
```py
results = Post.query.msearch(q, fields=['title', 'content'], limit=20)
print(results)

==> SELECT post.id AS post_id, post.title AS post_title, post.content AS post_content FROM post WHERE null                                      
```           

这是所有配置：
```py
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////' + base_path +'/test.db'
app.config.update(
    DEBUG=True,
    MSEARCH_INDEX_NAME='whoosh_index',
    MSEARCH_BACKEND='whoosh',
    MSEARCH_ENABLE=True
)
db = SQLAlchemy(app)
search = Search(db=db, analyzer=ChineseAnalyzer())
search.init_app(app)
```

**Comment by seale** [comment]
emmmm看了你的bbs项目，知道了是没有`search.create_index()`。我之前是写在`search.init_app(app)`下面的。然后我又单独在另一个文件执行就能成功创建索引。这里有点搞不明白.

**Comment by seale** [comment]
还有另外的疑问，测试时`search.create_index()`放在视图函数之前就可以，放在后面会报错（已调用 `search.init_app(app)`，）：
```py
AttributeError: 'function' object has no attribute 'create_index' 
```
然后现在就是没办法自动更新index，已经配置了 `MSEARCH_ENABLE=True`。本来想在视图函数里添加数据后就手动调用来更新，但也报了上面的错误。

**Comment by honmaple** [comment]
设置`SQLALCHEMY_TRACK_MODIFICATIONS = True`试试，或者model里是否添加了`__searchable__`.
另如果app与search可调用，可以直接`search = Search(app)`,不必再`search.init_app(app)`

**Comment by seale** [comment]
嗯我设置为True后就可以自动更新了，不过更新后还是会报个错
![error](https://user-images.githubusercontent.com/12511058/34647743-2862f96e-f3c6-11e7-97c0-ad5c77ed6e26.png)

**Comment by honmaple** [comment]
我没有遇到过这样的问题，你看一下是不是版本的原因，`pip install flask-msearch --upgrade`

**Comment by seale** [comment]
。。。。终于发现原因，石乐志了是视图函数习惯性命名导致重名了，之前没有认真排查。谢谢你的回答
